#data base connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_api
    username: root
    password: Santhu@7022
    driver-class-name: com.mysql.cj.jdbc.Driver
   
   
#JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
